controller_names:
  - fake_manipulator_contoller
fake_manipulator_controller:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:
  manipulator: allZeros
